name: publish-docker

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build . -t epicwink/seddy:${{ github.ref_name }}
    - name: Login to DockerHub
      run: >
        echo ${{ secrets.DOCKERHUB_PASSWORD }}
        | docker login --password-stdin -u epicwink
    - name: Publish image
      run: docker push epicwink/seddy:${{ github.ref_name }}
    - name: Check tag
      id: check-tag
      run: |
        if [[ "${{ github.ref_name }}" =~ '^v\d+\.\d+\.\d+$' ]]; then
            echo ::set-output name=match::true
        fi
    - name: Publish latest image
      if: steps.check-tag.outputs.match == 'true'
      run: |
        docker tag epicwink/seddy:${{ github.ref_name }} epicwink/seddy:latest
        docker push epicwink/seddy:latest
