name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ver/*
    tags:
      - v*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15-dev'
        include:
        - os: ubuntu-22.04
          python-version: '3.7'
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: pip install -U pip
    - name: Install dependencies
      run: pip install --requirement ./tests/requirements.txt black isort .
    - name: Lint with black
      run: |
        black --check src/
    - name: Lint imports with isort
      run: isort --check src/
    - name: Test with pytest
      run: |
        pytest -vvra --cov seddy --cov-report xml --cov-report term
